### ISSUE TITLE
checkReadability

### ISSUE THREAD

**Issue by brianteeman** [ryersondmp/sa11y#10]
testing everything and when I set sa11yCheckRoot to "main" instead of the  default "body" then the readability checks fail with this error

![image](https://user-images.githubusercontent.com/1296369/124808815-5409a880-df57-11eb-9179-d19fafbbf784.png)

You can see this in action https://a11y.brianstest.site/

**Comment by adamchaboryk** [comment]
Great catch. I'm annoyed I didn't catch this one myself.

Fixed.

For more flexibility, I'm not restricting it to main content area. You should be able to pass multiple selectors now. E.g. sa11yReadabilityRoot = "main, footer"

````javascript
//Target area to scan.
let sa11yCheckRoot = ""; //Default: body. Use "main" for main content.

//Readability configuration.
let sa11yReadabilityRoot = ""; //Default: main, [role='main'].
const sa11yReadabilityLang = "en"; //Supported: en = English, fr = French, es = Spanish

**Comment by brianteeman** [comment]
tested - all good

thanks
