### ISSUE TITLE
Expand readability test coverage

### ISSUE THREAD

**Issue by adamchaboryk** [ryersondmp/sa11y#13]
Look into ARI and AARI: https://www.researchgate.net/publication/289487170_AARI_Automatic_Arabic_readability_index

**Comment by brianteeman** [comment]
Also https://readable.com/blog/the-lix-and-rix-readability-formulas/ for other non-english languages

**Comment by adamchaboryk** [comment]
@brianteeman Found this repo, looks more comprehensive than current readability script. Also includes Rix. Going to look into it.

https://github.com/sahava/readability-score-javascript

**Comment by adamchaboryk** [comment]
Added LIX to readability module. Just need to do some more research on what other languages can be supported.

https://github.com/ryersondmp/sa11y/blob/v2.3.3-development/src/js/sa11y.js#L2872

@smncd, I also added a machine-translated Swedish demo page to assist with your translation/testing. If you have a moment, I'd appreciate a second set of eyes on the Lix function!

**Comment by smncd** [comment]
@adamchaboryk, saw it now, super! I've merged your changes into my translation branch, pretty much ready there. 
Looking through the Lix function now!

**Comment by adamchaboryk** [comment]
Merged! Thanks again, @smncd!

**Comment by smncd** [comment]
Comparing the Lix function to something like [lix.se](https://www.lix.se), the scores differ slightly:

Lix.se:
< 30 | Good/Very easy
30 - 40 | Good
40 - 50 | Fairly difficult
50 - 60 | Difficult
> 60 | Very difficult

**Comment by adamchaboryk** [comment]
@smncd, I'll adjust the if/else statements so it aligns with lix.se - otherwise, from the few passages of text I compared, it is almost the same!
