### ISSUE TITLE
input example 3

### ISSUE THREAD

**Issue by brianteeman** [ryersondmp/sa11y#14]
![image](https://user-images.githubusercontent.com/1296369/125257675-8fa8c780-e2f5-11eb-99d0-4d81ad21ccdb.png)

I assume that there is a bug here and that this should be marked as a warning?

**Comment by adamchaboryk** [comment]
Ehhh... I had the ruleset commented out (but forgot to hide Example 3). I was contemplating on whether to make this a warning or not. Although after consideration, I'm going to add it back in. I'll also display the accessible name of the input too. 

As I was addressing the above, I saw other issues with my ruleset logic... now fixed! Will be released in 2.0.7.

You're keeping me on my toes, Brian! 😅 Thanks again - I really appreciate the second set of eyes.
