### ISSUE TITLE
Bookmarklet blocked by CSP

### ISSUE THREAD

**Issue by willfarrell** [ryersondmp/sa11y#15]
```
Refused to load the script 'https://cdn.jsdelivr.net/gh/ryersondmp/sa11y@latest/bookmarklet/sa11y-en.min.js' because it violates the following Content Security Policy directive: "script-src 'self'".
```

Web pages that have a properly set Content-Security-Policy header will prevent bookmarklets from running. Might need to be bundled into a browser extension to allow usage on secured web pages. I expect it is still usable on localhost but haven't tested it yet.

Tested on: https://mackenziedatastream.ca and https://uwaterloo.ca

Extension resources:
- https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions
- https://github.com/mdn/webextensions-examples

**Comment by brianteeman** [comment]
Unfortunately that's a limitation of bookmarklets

**Comment by adamchaboryk** [comment]
Yes - it is a limitation as @brianteeman pointed out. I also have this disclaimer on the project page.

Eventually i'd like to roll out browser extensions to (hopefully) circumvent this.

**Comment by mandrasch** [comment]
> Eventually i'd like to roll out browser extensions to (hopefully) circumvent this.

Is this still planned? :) (Very cool that german language support was added, keep up the awesome work! 🎉)

**Comment by mandrasch** [comment]
btw: I'm wondering how WAVE solves this https://wave.webaim.org/report#/https://bahn.de , because sa11y bookmarklet is blocked by CSP on http://bahn.de, but WAVE is not. It this because of the iframe? 🤔
