### ISSUE TITLE
css important

### ISSUE THREAD

**Issue by brianteeman** [ryersondmp/sa11y#17]
now that all the css is much more specific does it really still need the !important

**Comment by adamchaboryk** [comment]
I know it's overkill in some places, although I guess it's there for redundancy (lol). It's just a bulletproof way of ensuring there's no conflicts across _every_ website. From my testing, the `all: unset;` hack doesn't capture _everything_. 

It would require a considerable amount of time to test which elements don't require !important (across various websites). 

Any reasons to remove the many instances of !important?

**Comment by brianteeman** [comment]
In general I believe it to be bad practice and can lead to further problems in the future but I guess for a utility like this its probably ok and not worth investing the time to check
