### ISSUE TITLE
Link check (advanced)

### ISSUE THREAD

**Issue by brianteeman** [ryersondmp/sa11y#25]
@adamchaboryk Re the change you made to advanced links

> Need a surrounding if (linkText !== null), otherwise empty links get both a warning and error flag.

I dont think that goes far enough. If you have an empty link but it has target=_blank you will still get a warning and an error.  

https://github.com/ryersondmp/sa11y/blob/1931c3b2a67f2e76f64bcd1279b503f17763d0fc/docs/examples/links-tables.html#L116-L117

However I am not sure what the problem is that you were trying to solve originally.

**Comment by adamchaboryk** [comment]
Thanks @brianteeman 

Yes, indeed doesn't go far enough. Although I think that's a very, very specific use case (empty link + target blank)... 

I was originally trying to fix:

````
<a href="https://www.google.com"></a>
<a href="https://www.bing.com"></a>
````

Which would show following screenshot:

<img width="320" alt="Screenshot of Sa11y flagging an empty hyperlink warning that it has same link text as another in addition to overlapping error flag." src="https://user-images.githubusercontent.com/26335725/145834939-fbb4869f-5d3d-4aef-9b2a-c92f529a8e17.png">
