### ISSUE TITLE
Adding types

### ISSUE THREAD

**Issue by smncd** [ryersondmp/sa11y#31]
Hello there! First off, great project!

I thought it'd be a good idea to introduce typings for importing Sa11y into Typescript files/projects. 
I've written up some types already, let me know if you'd be interested and I'll open a pull request.

**Comment by adamchaboryk** [comment]
Hi @smncd,

Thank you! My apologies for the slow reply.

I'm personally not too familiar with Typescript (so apologies for my ignorance!). If you are proposing the addition of just a Type Declaration file (without a massive rewrite of the library) - I'd be open to that if meant supporting the Typescript ecosystem! Feel free to open a PR.

P.S. I had a look at your fork, and noticed you started working on a Swedish translation. Awesome! I've been meaning to look into RIX/LIX for the readability module. I'll have to revisit it!

**Comment by smncd** [comment]
Hi @adamchaboryk !

No worries!

Yep, you're correct. I was really keen on changing things as little as possible to make it work, so it shouldn't interfere with how things currently work. I'll open a PR!

A possible RIX/LIX implemetation down the road sounds awesome!
