### ISSUE TITLE
Missing Table headlines. 

### ISSUE THREAD

**Issue by skerbis** [ryersondmp/sa11y#48]
Here I get the Error TABLES_MISSING_HEADINGS
But these are defined in the Table

<img width="1143" alt="Bildschirmfoto 2023-04-28 um 17 26 36" src="https://user-images.githubusercontent.com/791247/235189458-88b7849d-9e84-4307-86ab-f6ecca189583.png">

**Comment by brianteeman** [comment]
What does the source look like. You cant tell if there are any heading missing or not from the image

**Comment by skerbis** [comment]
oh sorry ... there is an empty table between. Sorry for that.

**Comment by brianteeman** [comment]
Proves it works ;)
