### ISSUE TITLE
scss lint

### ISSUE THREAD

**Issue by brianteeman** [ryersondmp/sa11y#53]
If you run the lint with the defined rules you get a LOT of errors. Most of this is because the lint hasn't been recently. But there are also two rules that are causing problems.

` "value-no-vendor-prefix": true`

This rule comes from Joomla but we also have as part of our build scripts something that checks to see if a vendor prefix is needed and adds it if needed.

```
		"property-disallowed-list": [
			"/left/",
			"/right/"
		],
```

I know why you made this rule but its creating a lot of _false positives_ where you have some absolute positions eg

```
src/scss/tooltips.scss
  59:3  ✖  Unexpected property "left"                 property-disallowed-list
  71:3  ✖  Unexpected property "left"                 property-disallowed-list
  78:3  ✖  Unexpected property "right"                property-disallowed-list
  82:3  ✖  Unexpected property "right"                property-disallowed-list
  84:3  ✖  Unexpected property "border-left-color"    property-disallowed-list
  89:3  ✖  Unexpected property "left"                 property-disallowed-list
  93:3  ✖  Unexpected property "left"                 property-disallowed-list
  95:3  ✖  Unexpected property "border-right-color"   property-disallowed-list
 260:5  ✖  Unexpected property "border-left-color"    property-disallowed-list
 264:5  ✖  Unexpected property "border-right-color"   property-disallowed-list
```

I could disable those two rules and then run `npx stylelint --config .stylelintrc.json -s scss "src/scss/**/*.scss" --fix  ` and submit a pr but not sure if that would mess with your own build process

**Comment by adamchaboryk** [comment]
I had a look...

So turns out my Stylelint extension was disabled, which explains why I wasn't seeing issues with my SCSS 🤦‍♂️

I also configured `autoprefixer` - another thing I forgot to setup, lol.

I think it's ok now. Do you mind taking a look?

https://github.com/ryersondmp/sa11y/tree/3.0.3-development

**Comment by adamchaboryk** [comment]
Good catch 

I've removed the copyright notices from /src/, and instead automated the copyright notices using rollup output. Also automated the version number on all pages within the /docs/

**Comment by brianteeman** [comment]
good stuff

**Comment by adamchaboryk** [comment]
Are you still looking over things? I think you mentioned potential RTL issues a while back — either way, i'll hold off on releasing for now

**Comment by brianteeman** [comment]
Now that you have fixed all that stuff I can check it properly ;)
Will do it on Sunday

**Comment by adamchaboryk** [comment]
No rush!! I greatly appreciate you having a look!

Cheers
