### ISSUE TITLE
Dark Mode colour filter

### ISSUE THREAD

**Issue by brianteeman** [ryersondmp/sa11y#54]
Clearly the dropdown has a problem when in dark mode

![image](https://github.com/ryersondmp/sa11y/assets/1296369/81e4548d-4d95-4bd4-967f-479c8b6f8f67)

**Comment by adamchaboryk** [comment]
Weird, only happening in Windows. I'll look into it, thanks!

**Comment by adamchaboryk** [comment]
What browser & OS combo are you using?

**Comment by brianteeman** [comment]
chrome, windows 11

**Comment by brianteeman** [comment]
when you tested were you changing everything (browser) to dark mode or just sa11y?
