### ISSUE TITLE
Contrast Check

### ISSUE THREAD

**Issue by brianteeman** [ryersondmp/sa11y#55]
![image](https://github.com/ryersondmp/sa11y/assets/1296369/bd809f0d-954e-46d8-aa18-e737a570964e)

![image](https://github.com/ryersondmp/sa11y/assets/1296369/5e42df0e-3f7c-4e56-ae1a-16b9adf1b185)

As you can see the css that highlights the text breaks the layout which no other sa11y indicator does.

**Comment by adamchaboryk** [comment]
I know it's a little unsightly, but decided to leave it as is for simplicity.

The `inline` prop changes the CSS styles applied to errors. Anything that is set to `inline: true` it changes the background colour. Which isn't helpful for contrast ruleset. I thought it was minor, so i didn't want to refactor it too much.

```
results.push({
    element: name,
    type: Constants.Global.ERROR,
   content: Lang.sprintf('CONTRAST_ERROR', cratio, sanitizedText),
   inline: false,
   position: 'beforebegin',
});
```

Screenshot attached when `inline` set to `true`.
<img width="488" alt="Screenshot of contrast issue where the error highlighting hides the actual colour causing the contrast issue." src="https://github.com/ryersondmp/sa11y/assets/26335725/fdd338cb-3f7b-47e1-93cd-e9dc6079c1dd">
