### ISSUE TITLE
Missing Outline Level

### ISSUE THREAD

**Issue by brianteeman** [ryersondmp/sa11y#56]
It used to be indicated as a red x as still can be seen on the home page screenshots
![image](https://github.com/ryersondmp/sa11y/assets/1296369/50790244-8693-497f-ad8d-51b6f8c14b67)

It is now an ! which to me doesnt look as clear,

![image](https://github.com/ryersondmp/sa11y/assets/1296369/e0678960-4a44-431b-9a24-a9a88f2f5591)

**Comment by adamchaboryk** [comment]
i'll change it back to `⚠️` and use the proper entity so it doesn't convert into an emoji `&#x26A0;`

**Comment by adamchaboryk** [comment]
Nvm, i used the FontAwesome icon — it will look good. Will update dev shortly
