### ISSUE TITLE
Heading check misses first instance of large bold text following a heading.

### ISSUE THREAD

**Issue by gregrgay** [ryersondmp/sa11y#71]
Might be a bug in the "Is this a heading" check. I have a page with two bold one word paragraphs ending in a colon, separated by a paragraph of text. In the example below, only "Disadvantages:" gets flagged. It happens when the first instance follows a heading of any level, but not if it appears after something else.

e.g. 
<h1>[the main heading]</h1>
<p><strong>Advantages:</strong></p>
<p>[some more text content]</p>
<p><strong>Disadvantages:</strong></p>
<p>[some more text content]</p>

Looking at src/js/rulesets/quality-assurance line #198 I see  ignoresElements contains all the heading levels and ignores them for this check. Removing the H1 & H2 from the list fixes the issue for our purposes, though not sure what else that would affect. My thinking is headings should be removed from the list. Not sure if there's some other reason why bold text after headings should be ignored.

There will be scenarios where two or more headings, of different levels, follow in sequence.

**Comment by adamchaboryk** [comment]
Fake heading detection logic was improved in version `3.0.6` — although the rationale for this old logic was to minimize false positives/excessive warnings. 

New fake heading logic doesn't check for what the previous element is!
