### ISSUE TITLE
Outline text detection

### ISSUE THREAD

**Issue by brianteeman** [ryersondmp/sa11y#73]
## How to reproduce

Create a basic html page as below and use the sa11y bookmark

```
<html lang="en">
    <head>
        <title>Language Check H1</title>
    </head>
    <body>
        <h1>
            <svg viewBox="0 0 10 10" xmlns="http://www.w3.org/2000/svg">
                <style>
                  circle {
                    fill: gold;
                    stroke: maroon;
                    stroke-width: 2px;
                  }
                </style>
                <circle cx="5" cy="5" r="4" />
            </svg>
             test
	</h1>
    </body>
</html>
```

### Expected Result
![image](https://github.com/ryersondmp/sa11y/assets/1296369/d66742b7-46ca-4195-bcbe-6fe2a9c1c622)

### Actual Result
![image](https://github.com/ryersondmp/sa11y/assets/1296369/ad7cb4f8-6588-4425-bf1c-7c28d2b940ee)

**Comment by adamchaboryk** [comment]
Huh. I thought I excluded `<style>` tags already, I should also test `<noscript>` too while I'm at it. Thanks for the bug report @brianteeman, I'll have this fixed shortly!

**Comment by adamchaboryk** [comment]
Fixed!
