### ISSUE TITLE
booklet

### ISSUE THREAD

**Issue by brianteeman** [ryersondmp/sa11y#76]
Don't know if these are possible but I thought I should ask.

1. I find that after clicking on the booklet to turn it on I am then clicking on it again to try and turn it off and of course get the message "Sa11y is already loaded on this page. Please wait, or reload the page and try again." Would it be possible to have a it work the way my brian is working and have the second click simply turn off sally.

2. On pages where the booklet wont work eg here at github because of the csp is it possible to display an alert. Otherwise someone might just think sa11y doesnt work at all.

**Comment by adamchaboryk** [comment]
Hmm, this is great feedback. Thanks again @brianteeman!

1 should be doable, I'll look into it. 

As for 2, I did a little research. I thought this was impossible initially, but it looks like WebAim figured it out with their [contrast bookmarklet!](https://webaim.org/resources/contrastchecker/bookmarklet#:~:text=and%20background%20colors.-,Quick%20Installation,-Drag%20the%20link) 

TIL there's an [event for securitypolicyviolation.](https://developer.mozilla.org/en-US/docs/Web/API/Element/securitypolicyviolation_event)

Adding this to the to-do list!

**Comment by brianteeman** [comment]
Thats great news.

**Comment by brianteeman** [comment]
awesome stuff -- love it!!

**Comment by adamchaboryk** [comment]
Shipped! TY once again for the great feedback, @brianteeman. I also tinkered with the language files, so it injects the right locale based on page lang. One less thing to include in build step, and better UX for all.
