### ISSUE TITLE
List false positives in table cells

### ISSUE THREAD

**Issue by gregrgay** [ryersondmp/sa11y#80]
We're finding a lot of list false positives in table cells, like those in the attached screenshot. Not sure why some, but not others. Times (e.g. 11:00 pm) get flagged, for instance, but not the row headers that have a "1. Bedtime" value, which looks more like a list item but isn't flagged. Would removing the check for paragraphs that start with numbers in table cells help remedy the issue? 
![listFPs](https://github.com/ryersondmp/sa11y/assets/898756/88b928c0-2db2-4b71-965f-e1946de8825a)

There are cases where a cell might have a list in it, so perhaps one of the parameters for the check could be if there is more than one paragraph in a cell that starts with a number, flag as a possible list, otherwise ignore it. etc.

Here's the markup for the table to experiment with:

<table cellspacing="0" cellpadding="0" bordercolor="#000000" border="1" summary="Table has 8 columns and 6 rows. Read each column from top to bottom for sleep diary details for each day of the week." style="width: 100%;">
<caption>  Table 9.1: Sleep Diary</caption>
<thead>
<tr>
<th valign="top">  &#160;</th>
<th valign="top">   <p>Monday</p>
</th>
<th valign="top">   <p>Tuesday</p>
</th>
<th valign="top">   <p>Wednesday</p>
</th>
<th valign="top">   <p>Thursday</p>
</th>
<th valign="top">   <p>Friday</p>
</th>
<th valign="top">   <p>Saturday</p>
</th>
<th valign="top">   <p>Sunday</p>
</th>
</tr>
</thead>
<tbody>
<tr>
<th valign="top">   <p>1. Bedtime</p>
</th>
<td valign="top">   <p>11:00 pm</p>
</td>
<td valign="top">   <p>11:30 pm</p>
</td>
<td valign="top">   <p>11:05 pm</p>
</td>
<td valign="top">   <p>10:35 pm</p>
</td>
<td valign="top">   <p>10:55 pm</p>
</td>
<td valign="top">   <p>12:15 am</p>
</td>
<td valign="top">   <p>10:15 pm</p>
</td>
</tr>
<tr>
<th valign="top">   <p>2. Time to fall asleep</p>
</th>
<td>   <p>25</p>
</td>
<td>   <p>20</p>
</td>
<td>   <p>40</p>
</td>
<td>   <p>60</p>
</td>
<td>   <p>35</p>
</td>
<td>   <p>15</p>
</td>
<td>   <p>95</p>
</td>
</tr>
<tr>
<th valign="top">   <p>3. Time awake during night</p>
</th>
<td>   <p>20</p>
</td>
<td>   <p>25</p>
</td>
<td>   <p>15</p>
</td>
<td>   <p>35</p>
</td>
<td>   <p>20</p>
</td>
<td>   <p>45</p>
</td>
<td>   <p>60</p>
</td>
</tr>
<tr>
<th valign="top">   <p>4. Wake time</p>
</th>
<td valign="top">   <p>7 am</p>
</td>
<td valign="top">   <p>7 am</p>
</td>
<td valign="top">   <p>7 am</p>
</td>
<td valign="top">   <p>7 am</p>
</td>
<td valign="top">   <p>7 am</p>
</td>
<td valign="top">   <p>8:40 am</p>
</td>
<td valign="top">   <p>7:50 am</p>
</td>
</tr>
<tr>
<th valign="top">   <p>5. Rise time</p>
</th>
<td valign="top">   <p>7:15 am</p>
</td>
<td valign="top">   <p>7:20 am</p>
</td>
<td valign="top">   <p>7 am</p>
</td>
<td valign="top">   <p>7:25 am</p>
</td>
<td valign="top">   <p>7:15 am</p>
</td>
<td valign="top">   <p>10:50 am</p>
</td>
<td valign="top">   <p>11:45 am</p>
</td>
</tr>
</tbody>
</table>

**Comment by adamchaboryk** [comment]
Thanks, Greg. I'll look into it

**Comment by adamchaboryk** [comment]
Fixed!

**Comment by gregrgay** [comment]
Though the issue has been largely fixed, I did come across another instance, but don't see what's causing it. There are a couple other similar table on the same page, that do not get flagged. 

![screen1](https://github.com/ryersondmp/sa11y/assets/898756/b7262109-f54d-4d6e-bfe1-5a666d0b6cba)

Here's the markup for the offending table.

<table border="1" cellpadding="0" cellspacing="0" style="width: 100%;">
	<thead>
		<tr>
			<th valign="top" width="158">
			<p align="center">Price</p>
			</th>
			<th valign="top" width="158">
			<p align="center">Quantity Demanded</p>
			</th>
			<th valign="top" width="158">
			<p align="center">Total Revenue</p>
			</th>
			<th valign="top" width="158">
			<p align="center">Marginal Revenue</p>
			</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td valign="top" width="158">
			<p align="center">7</p>
			</td>
			<td valign="top" width="158">
			<p align="center">0</p>
			</td>
			<td valign="top" width="158">
			<p align="center">0</p>
			</td>
			<td valign="top" width="158">
			<p align="center">NA</p>
			</td>
		</tr>
		<tr>
			<td valign="top" width="158">
			<p align="center">6.50</p>
			</td>
			<td valign="top" width="158">
			<p align="center">1</p>
			</td>
			<td valign="top" width="158">
			<p align="center">6.50</p>
			</td>
			<td valign="top" width="158">
			<p align="center">6.50</p>
			</td>
		</tr>
		<tr>
			<td valign="top" width="158">
			<p align="center">6</p>
			</td>
			<td valign="top" width="158">
			<p align="center">2</p>
			</td>
			<td valign="top" width="158">
			<p align="center">12</p>
			</td>
			<td valign="top" width="158">
			<p align="center">5.50</p>
			</td>
		</tr>
		<tr>
			<td valign="top" width="158">
			<p align="center">5.50</p>
			</td>
			<td valign="top" width="158">
			<p align="center">3</p>
			</td>
			<td valign="top" width="158">
			<p align="center">16.50</p>
			</td>
			<td valign="top" width="158">
			<p align="center">4.50</p>
			</td>
		</tr>
		<tr>
			<td valign="top" width="158">
			<p align="center">5</p>
			</td>
			<td valign="top" width="158">
			<p align="center">4</p>
			</td>
			<td valign="top" width="158">
			<p align="center">20</p>
			</td>
			<td valign="top" width="158">
			<p align="center">3.50</p>
			</td>
		</tr>
		<tr>
			<td valign="top" width="158">
			<p align="center">4.50</p>
			</td>
			<td valign="top" width="158">
			<p align="center">5</p>
			</td>
			<td valign="top" width="158">
			<p align="center">22.50</p>
			</td>
			<td valign="top" width="158">
			<p align="center">2.50</p>
			</td>
		</tr>
		<tr>
			<td valign="top" width="158">
			<p align="center">4</p>
			</td>
			<td valign="top" width="158">
			<p align="center">6</p>
			</td>
			<td valign="top" width="158">
			<p align="center">24</p>
			</td>
			<td valign="top" width="158">
			<p align="center">1.50</p>
			</td>
		</tr>
		<tr>
			<td valign="top" width="158">
			<p align="center">3.50</p>
			</td>
			<td valign="top" width="158">
			<p align="center">7</p>
			</td>
			<td valign="top" width="158">
			<p align="center">24.50</p>
			</td>
			<td valign="top" width="158">
			<p align="center">0.50</p>
			</td>
		</tr>
		<tr>
			<td valign="top" width="158">
			<p align="center">3</p>
			</td>
			<td valign="top" width="158">
			<p align="center">8</p>
			</td>
			<td valign="top" width="158">
			<p align="center">24</p>
			</td>
			<td valign="top" width="158">
			<p align="center">–0.50</p>
			</td>
		</tr>
		<tr>
			<td valign="top" width="158">
			<p align="center">2.50</p>
			</td>
			<td valign="top" width="158">
			<p align="center">9</p>
			</td>
			<td valign="top" width="158">
			<p align="center">22.50</p>
			</td>
			<td valign="top" width="158">
			<p align="center">–1.50</p>
			</td>
		</tr>
	</tbody>
</table>

**Comment by itmaybejj** [comment]
Hmmph ok I'll take a look

**Comment by itmaybejj** [comment]
@adamchaboryk this is only hitting in Sa11y. Check
https://github.com/ryersondmp/sa11y/blob/master/src/js/utils/elements.js#L58 -- I select for p:not(table p).

**Comment by adamchaboryk** [comment]
Thanks for catching, @itmaybejj!!
