### ISSUE TITLE
Language Detection

### ISSUE THREAD

**Issue by brianteeman** [ryersondmp/sa11y#84]
I was testing the bookmarklet and came across a language issue.

The site I was checking is in german so sa11y loaded in german

But realistically instead of detecting the language of the site it would be better (at least for me) if it was detecting the language of the browser. Failing that then there should be an option in the popup so that I can switch to english. Otherwise sa11y is pretty useless to me for non-english sites as like most Brits I only speak english.

For testing pourposes this is the site I was looking at https://e4.bike

**Comment by nmerget** [comment]
This will help https://sa11y.netlify.app/bookmarklet/#english-only-version :)

**Comment by brianteeman** [comment]
ah - ok thanks
