### ISSUE TITLE
Missing check on hidden images

### ISSUE THREAD

**Issue by gregrgay** [ryersondmp/sa11y#90]
Since updating to 3.2.0 I'm noticing images contained within a hidden panel are not being picked up. It used to find them. Here's an example on our dev server (login required) of a click & reveal and an accordion panel. Also seems to occur with the flipcard panels as well. I'm guessing it's occurring with all embedded learning objects in the Ektron context.

I've setup some examples at:
https://de.spi.torontomu.ca/de_courses/templates/m/?c=211C1E0B83B9C69FA9C4BDEDE203C1E3&m=4&p=40204

**Comment by adamchaboryk** [comment]
Looks like you're ignoring the `.lo` container via props: `containerIgnore: '[class^=MathJax], .lo',`

So the entire container is not being checked for issues:

`<div class="lo flip-container" role="region" aria-live="polite" tabindex="0"><div class="flip-card">...</div>`

**Comment by gregrgay** [comment]
Good catch. Ignore .lo should just be for inline styles.
