### ISSUE TITLE
Click Here Check Issue

### ISSUE THREAD

**Issue by gregrgay** [ryersondmp/sa11y#98]
I came across this issue with a "click here" link flagged with a green check mark, though it seems like it should be a warning. It appears to read the aria label, and accept it as an alternative to the "click here", though in this case the label is not an effective/meaningful replacement for the meaningless link (it's being used as an example of a bad link in this case). I don't think any instance of "click here", even with a label, should be acceptable. I would judge it as an error, though a warning when a label is present may be okay.

![clickhere](https://github.com/user-attachments/assets/158be787-a542-4ad4-9717-77f3118e7e73)

HTML
<p>Example: Instead of “<a href="https://www.britannica.com/biography/George-Orwell" title="Click here" target="DES" aria-label="Incorrect hyperlink formatting">Click here</a> to learn more about George Orwell”, you could write “Delve into the life and works of <a href="https://www.britannica.com/biography/George-Orwell" title="George Orwell at Britannica" target="DES">George Orwell at Britannica</a>.”</p>

**Comment by adamchaboryk** [comment]
New warning will be added in 4.0!
